# Generated by Django 3.2.4 on 2021-06-22 19:51

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210622_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to='media'),
        ),
    ]
