# Generated by Django 3.2.4 on 2021-06-22 20:14

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210622_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to='size'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to='size'),
        ),
    ]
